INSERT INTO AUTHOR (AUTHOR_ID,AUTHOR_NAME,PHONE_NUMBER) VALUES (1,'Sam Jones', 254722);
INSERT INTO AUTHOR (AUTHOR_ID,AUTHOR_NAME,PHONE_NUMBER) VALUES (2,'Jane Jill', 254733);
INSERT INTO AUTHOR (AUTHOR_ID,AUTHOR_NAME,PHONE_NUMBER) VALUES (3,'John Smith', 254232);
INSERT INTO AUTHOR (AUTHOR_ID,AUTHOR_NAME,PHONE_NUMBER) VALUES (4,'Mike Kimani', 254323);
INSERT INTO BOOK (BOOK_ID,BOOK_TITLE,AUTHOR_ID,BOOK_PUBLISHER,BOOK_SUBJECT,BOOK_ISBN,BOOK_LENGTH)
VALUES (10,'Princess Diaries',2,'Mototo Publishers','Fantasy',900,1059);
INSERT INTO BOOK (BOOK_ID,BOOK_TITLE,AUTHOR_ID,BOOK_PUBLISHER,BOOK_SUBJECT,BOOK_ISBN,BOOK_LENGTH)
VALUES (20,'Jack and Jill',4,'Wazee Publishers','True Story',901,1000);
INSERT INTO BOOK (BOOK_ID,BOOK_TITLE,AUTHOR_ID,BOOK_PUBLISHER,BOOK_SUBJECT,BOOK_ISBN,BOOK_LENGTH)
VALUES (30,'Crossing the Bridge',3,'Maji Moto Publishers','Romance',902,2007);